### ISSUE TITLE
Build instructions fail

### ISSUE THREAD

**Issue by yurivict** [legatoproject/legato-af#10]
```
curl https://storage.googleapis.com/git-repo-downloads/repo > repo &&
> chmod a+x ./repo &&
> mkdir workspace &&
> cd workspace &&
> ../repo init -u git://github.com/legatoproject/manifest &&
> ../repo sync
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27759  100 27759    0     0   321k      0 --:--:-- --:--:-- --:--:--  322k
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Finding sources: 100% (6/6)
remote: Total 6 (delta 3), reused 6 (delta 3)
Unpacking objects: 100% (6/6), done.
From https://gerrit.googlesource.com/git-repo
   b881d22..bb9c42c  master     -> origin/master
Get git://github.com/legatoproject/manifest
remote: Counting objects: 31, done.        
remote: Total 31 (delta 0), reused 0 (delta 0), pack-reused 31        
From git://github.com/legatoproject/manifest
 * [new branch]      master     -> origin/master

Your identity is: Gogs <gogs@fake.local>
If you want to change this, please re-run 'repo init' with --config-name

repo has been initialized in /usr/ports/net-p2p/legato/workspace
Fetching project legato-PlatformAdaptor-QmiBin-wp750x
Fetching project legato-PlatformAdaptor-QmiBin-ar758x
Fetching project legato-PlatformAdaptor-Audio
Fetching project legato-PlatformAdaptor-Simu
Fetching project legato-PlatformAdaptor-QmiBin-wp85
remote: Counting objects: 346, done.        
remote: Counting objects: 241, done.               
remote: Counting objects: 227, done.        
remote: Compressing objects: 100% (20/20), done.        
remote: Compressing objects: 100% (35/35), done.        
remote: Total 227 (delta 19), reused 0 (delta 0), pack-reused 181        
Receiving objects: 100% (227/227), 99.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (117/117), done.
From git://github.com/legatoproject/legato-PlatformAdaptor-Simu
 * [new branch]      master     -> legato/master
 * [new tag]         16.04.1    -> 16.04.1
 * [new tag]         16.07.0    -> 16.07.0
remote: Counting objects: 25, done.        
remote: Total 25 (delta 0), reused 0 (delta 0), pack-reused 25        
From git://github.com/legatoproject/legato-PlatformAdaptor-Audio
 * [new branch]      master     -> legato/master
 * [new tag]         16.04.1    -> 16.04.1
 * [new tag]         16.07.0    -> 16.07.0
Fetching projects:   8% (1/12)  Fetching project legato-af
Fetching projects:  16% (2/12)  Fetching project legato-PlatformAdaptor-QmiBin-ar7
remote: Total 346 (delta 8), reused 0 (delta 0), pack-reused 321        
remote: Counting objects: 324, done.        
remote: Counting objects: 15991, done.             
remote: Total 241 (delta 0), reused 0 (delta 0), pack-reused 241        
Receiving objects: 100% (241/241), 776.97 KiB | 645.00 KiB/s, done.
Resolving deltas: 100% (125/125), done.
From git://github.com/legatoproject/legato-PlatformAdaptor-QmiBin-ar758x
 * [new branch]      master     -> legato/master
 * [new tag]         16.04.1    -> 16.04.1
 * [new tag]         16.07.0    -> 16.07.0
Receiving objects: 100% (346/346), 876.08 KiB | 911.00 KiB/s, done.
Fetching projects:  25% (3/12)  Fetching project legato-Raspi
remote: Compressing objects: 100% (20/20), done.        
Resolving deltas: 100% (203/203), done.
remote: Compressing objects: 100% (96/96), done.        
From git://github.com/legatoproject/legato-PlatformAdaptor-QmiBin-wp750x
 * [new branch]      master     -> legato/master
 * [new tag]         16.07.0    -> 16.07.0
Fetching projects:  33% (4/12)  Fetching project legato-PlatformAdaptor-QmiBin-ar759x
remote: Counting objects: 329, done.        
remote: Counting objects: 25, done.        
remote: Total 25 (delta 0), reused 0 (delta 0), pack-reused 25        
From git://github.com/legatoproject/legato-Raspi
 * [new branch]      master     -> legato/master
 * [new tag]         16.07.0    -> 16.07.0
Fetching projects:  41% (5/12)  Fetching project legato-PlatformAdaptor-AT
remote: Counting objects: 323, done.        
remote: Total 324 (delta 8), reused 0 (delta 0), pack-reused 299        
Receiving objects: 100% (324/324), 931.69 KiB | 927.00 KiB/s, done.
Resolving deltas: 100% (189/189), done.
From git://github.com/legatoproject/legato-PlatformAdaptor-QmiBin-ar7
 * [new branch]      master     -> legato/master
 * [new tag]         16.04.1    -> 16.04.1
 * [new tag]         16.07.0    -> 16.07.0
Fetching projects:  50% (6/12)  Fetching project legato-WiFi
remote: Counting objects: 320, done.        
remote: Total 329 (delta 0), reused 0 (delta 0), pack-reused 329        
Receiving objects: 100% (329/329), 791.34 KiB | 652.00 KiB/s, done.
remote: Total 320 (delta 0), reused 0 (delta 0), pack-reused 320        
Receiving objects: 100% (320/320), 142.33 KiB | 0 bytes/s, done.
Resolving deltas: 100% (173/173), done.
Resolving deltas: 100% (196/196), done.
From git://github.com/legatoproject/legato-PlatformAdaptor-AT
 * [new branch]      master     -> legato/master
 * [new tag]         16.04.1    -> 16.04.1
 * [new tag]         16.07.0    -> 16.07.0
From git://github.com/legatoproject/legato-PlatformAdaptor-QmiBin-wp85
 * [new branch]      master     -> legato/master
 * [new tag]         16.04.1    -> 16.04.1
 * [new tag]         16.07.0    -> 16.07.0
Fetching projects:  58% (7/12)  Fetching project legato-PlatformAdaptor-QmiBin-wp76xx
Fetching projects:  66% (8/12)  remote: Total 323 (delta 0), reused 0 (delta 0), pack-reused 323        
Receiving objects: 100% (323/323), 823.30 KiB | 664.00 KiB/s, done.
remote: Counting objects: 786, done.        
Resolving deltas: 100% (196/196), done.
From git://github.com/legatoproject/legato-PlatformAdaptor-QmiBin-ar759x
 * [new branch]      master     -> legato/master
 * [new tag]         16.04.1    -> 16.04.1
 * [new tag]         16.07.0    -> 16.07.0
Fetching projects:  75% (9/12)  remote: Counting objects: 113, done.        
remote: Compressing objects: 100% (12/12), done.        
remote: Total 786 (delta 0), reused 0 (delta 0), pack-reused 786        
Receiving objects: 100% (786/786), 286.92 KiB | 0 bytes/s, done.
Resolving deltas: 100% (420/420), done.
From git://github.com/legatoproject/legato-WiFi
 * [new branch]      master     -> legato/master
 * [new tag]         16.04.1    -> 16.04.1
 * [new tag]         16.07.0    -> 16.07.0
Fetching projects:  83% (10/12)  remote: Total 113 (delta 4), reused 0 (delta 0), pack-reused 98        
Receiving objects: 100% (113/113), 433.19 KiB | 721.00 KiB/s, done.
Resolving deltas: 100% (50/50), done.
From git://github.com/legatoproject/legato-PlatformAdaptor-QmiBin-wp76xx
 * [new branch]      master     -> legato/master
Fetching projects:  91% (11/12)  remote: Total 15991 (delta 20), reused 0 (delta 0), pack-reused 15893        
Receiving objects: 100% (15991/15991), 25.20 MiB | 5.12 MiB/s, done.
Resolving deltas: 100% (7824/7824), done.
From git://github.com/legatoproject/legato-af
 * [new branch]      master           -> legato/master
 * [new tag]         14.04.0.Beta.rc3 -> 14.04.0.Beta.rc3
 * [new tag]         14.04.1.Beta     -> 14.04.1.Beta
 * [new tag]         14.07.0.Beta     -> 14.07.0.Beta
 * [new tag]         14.10.0.Beta     -> 14.10.0.Beta
 * [new tag]         14.10.1.Beta     -> 14.10.1.Beta
 * [new tag]         15.01.0.Beta     -> 15.01.0.Beta
 * [new tag]         15.05.0.Beta     -> 15.05.0.Beta
 * [new tag]         15.08.1.Beta     -> 15.08.1.Beta
 * [new tag]         15.10.0.Beta     -> 15.10.0.Beta
 * [new tag]         15.10.1.Beta     -> 15.10.1.Beta
 * [new tag]         15.10.2.Beta     -> 15.10.2.Beta
 * [new tag]         16.01.2          -> 16.01.2
 * [new tag]         16.04.0          -> 16.04.0
 * [new tag]         16.04.1          -> 16.04.1
 * [new tag]         16.07.0          -> 16.07.0
Fetching projects: 100% (12/12), done.  
Traceback (most recent call last):
  File "/usr/ports/net-p2p/legato/workspace/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/usr/ports/net-p2p/legato/workspace/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/usr/ports/net-p2p/legato/workspace/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/usr/ports/net-p2p/legato/workspace/.repo/repo/subcmds/sync.py", line 821, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/usr/ports/net-p2p/legato/workspace/.repo/repo/project.py", line 1327, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync)
  File "/usr/ports/net-p2p/legato/workspace/.repo/repo/project.py", line 2480, in _InitWorkTree
    _lwrite(os.path.join(dotgit, HEAD), '%s\n' % self.GetRevisionId())
  File "/usr/ports/net-p2p/legato/workspace/.repo/repo/project.py", line 1312, in GetRevisionId
    rev = rem.ToLocal(self.revisionExpr)
  File "/usr/ports/net-p2p/legato/workspace/.repo/repo/git_config.py", line 679, in ToLocal
    raise GitError('remote %s does not have %s' % (self.name, rev))
error.GitError: remote legato does not have refs/heads/master
```

- on FreeBSD 11

**Comment by CoRfr** [comment]
git-repo is not really tested on FreeBSD as far as I know.

As for Legato, the only recommended development platform is Ubuntu (starting at 12.04), as you can see on the 'Dependencies': https://github.com/legatoproject/legato-af#dependencies

Internally we test that it builds on few platforms (such as Ubuntu, Debian, ArchLinux or Fedora), but it's only GNU/Linux distributions.
